#!/bin/bash

glib-compile-resources exampleapp.gresource.xml --target=resources.c --generate-source
wynik=$(echo $1 | sed -e "s/\..*//")
gcc --std=c11 --pedantic -Wall -Wextra `pkg-config --cflags gtk+-3.0` *.c -g -o $wynik `pkg-config --libs gtk+-3.0`
glib-compile-schemas .
GSETTINGS_SCHEMA_DIR=. gdb --args $wynik main.c exampleapp.h

